#!/usr/bin/env ruby
begin
  RAILS_ENV = ( ENV['RAILS_ENV'] || "production" )
  require File.dirname(__FILE__) + '/../config/boot'
  require RAILS_ROOT + '/config/environment'

  require "mq"

  mq_server = `git config hooks.queueserver`.chomp
  mq_user   = `git config hooks.queueuser`.chomp
  mq_pass   = `git config hooks.queuepassword`.chomp

  EM.run do
    connection = AMQP.connect(:host => mq_server, :user => mq_user, :pass => mq_pass)
    amq = MQ.new(connection)
    
    amq.queue("redmine-repo-update").subscribe do |repo_name|
      puts "#{Time.now.inspect} -- updating #{repo_name}"
      r = Repository.find(:first, :conditions => ["url LIKE ?", "%"+repo_name])
      if r
        r.fetch_changesets
        puts "#{Time.now.inspect} -- #{repo_name} update complete"
      else
        puts "#{Time.now.inspect} -- uhoh, couldn't find repo named '#{repo_name}'"
      end
    end
  end

rescue Interrupt
  puts "quitting..."
  exit
end
